### ISSUE TITLE
Can't connect with socket

### ISSUE THREAD

**Issue by MervinDelfin** [nosborn/homebridge-platform-gira-homeserver#1]
Hi, I'm getting an error:
`Error: Client network socket disconnected before secure TLS connection was established`

I know you said the project is only alpha quality. I think the a have the problem because the password is not getting hashed. Do you have a workaround for now?

Are you going to continue working on this project? I'm very interested.

**Comment by nosborn** [comment]
@MervinDelfin I no longer have access to a Gira HomeServer so I won't be doing any more work on this.
